# from repo root:
# docker-compose -f .docker/docker_manifest.yaml -p booking up --build

networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/aspnet_local.dockerfile
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=BookingData;Username=postgres;Password=BookingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - locally
    ports:
      - 8001:80

  data:
    environment:
      POSTGRES_PASSWORD: BookingData@2020
    image: postgres:12
    networks:
      - locally

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9412:9411

version: '3.8'
