networks:
  bookingly:

services:
  rest:
    image: ghcr.io/rvtr/rvtrx-api-booking:main-aspnet-rest
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=BookingData;Username=postgres;Password=LocalState@2021;'
    networks:
      - bookingly
    ports:
      - 8001:80

  data:
    environment:
      POSTGRES_PASSWORD: LocalState@2021
    image: postgres:13-alpine
    networks:
      - bookingly
    volumes:
      - bookingstore:/var/lib/postgresql/data

version: '3.8'

volumes:
  bookingstore:
