networks:
  bookingly:

services:
  rest:
    image: ghcr.io/rvtr/rvtrx-api-booking:main-aspnet-rest
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=BookingData;Username=postgres;Password=BookingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - bookingly
    ports:
      - 8001:80

  data:
    environment:
      POSTGRES_PASSWORD: BookingData@2020
    image: postgres:12
    networks:
      - bookingly

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - bookingly
    ports:
      - 9001:9411

version: '3.8'
